### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by nonameolsson** [ben-rogerson/babel-plugin-twin#4]
Hi! Great plugin!

How can I use it in a TypeScript project? 

The problem is shown in the screenshot below. `tw` is not found by TypeScript, and then the code can't compile.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1493018/128133819-2daf0b8f-2e60-4ea0-ae84-c4efda20684d.png">
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/1493018/128133904-9794d5a5-63f0-40fd-a5b1-96aed9974fbd.png">

**Comment by ben-rogerson** [comment]
Hey there

Ah, I think there's confusion between two features of the same name (how could that ever be confusing 😆):

**The tw prop**
`<div tw="block" />`
This plugin (babel-plugin-twin) adds the tw prop for you, no need to add a twin.macro import.

**The tw import**
```tw.div`block` ```
```tw`block`  ```
This is what you're using in the screenshot.
You'll need to import `tw` from twin:
`import tw from 'twin.macro'`

**Comment by nonameolsson** [comment]
Thank you @ben-rogerson for your reply! Then I understand better!

So this plugin "only" adds `tw` prop import in components, but `tw` used in `styled-components`?

**Comment by ben-rogerson** [comment]
>So this plugin "only" adds tw prop import in components

Yes, that's right

>but tw used in styled-components?

tw is imported through `twin.macro`

```js
import tw from 'twin.macro'
```
