### ISSUE TITLE
[Request] Ability to override custom components using the `tw` macro

### ISSUE THREAD

**Issue by ryall** [ben-rogerson/babel-plugin-twin#7]
It'd be great to be able to pass additional styles to more complex components (not wrapped with styled-component/emotion syntax). 

For example:

```ts
function Button() {
   // ...logic...
   
  return <div tw="bg-white text-xs"><span>Inner</span>-<span>content</span></div>;
}

<Button tw="bg-black" />
```

Right now it outputs: 
`<div tw="bg-white text-xs"><span>Inner</span>-<span>content</span></div>`

It would be nice if it instead output: 
`<div tw="bg-white text-xs bg-black"><span>Inner</span>-<span>content</span></div>` 
(with `bg-black` appended to the root node).

I know I can pass this as a custom prop but this would just be easier.

**Comment by ben-rogerson** [comment]
Not sure if you've tried this, but the styles added to the Button component can be passed down to the `div` element with the className prop:

```js
function Button({ className }) {
   // ...logic...
   
  return <div tw="bg-white text-xs" {...{ className }}><span>Inner</span>-<span>content</span></div>;
}

<Button tw="bg-black" />
```

**Comment by ryall** [comment]
Oh great, thank you!
